.\" -*-nroff-*-
.\"
.\"
.\"    Copyright (c) 2006,2007 Nokia Corporation
.\"    All rights reserved.
.\"    
.\"    Redistribution and use in source and binary forms, with or without
.\"    modification, are permitted provided that the following conditions are
.\"    met:
.\"    
.\"    * Redistributions of source code must retain the above copyright
.\"      notice, this list of conditions and the following disclaimer.
.\"    * Redistributions in binary form must reproduce the above copyright
.\"      notice, this list of conditions and the following disclaimer in the
.\"      documentation and/or other materials provided with the distribution.
.\"    * Neither the name of the Nokia Corporation nor the names of its
.\"      contributors may be used to endorse or promote products derived from
.\"      this software without specific prior written permission.
.\"    
.\"    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
.\"    IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\"    TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
.\"    PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
.\"    OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\"    EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\"    PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
.\"    PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\"    LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\"    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\"    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"    
.\"
.TH modest 1 "November 2007" Unix "User Manuals"
.SH NAME
modest \- The Modest Mail User Agent
.SH SYNOPSIS
.PP
.B modest 
[showui] 
.SH DESCRIPTION
.PP
Modest is a graphical e-mail program, targetting resource-constrained
environments, such as older PCs and internet tablets. It aims to be
easy to use and provide a complete e-mail experience, while keeping
the resource usage at a modest level (by 2007 standards).
.SH OPTIONS
.PP
.IP "showui"
To actually start with the UI, you have to provide the 'showui' parameter to
modest. Reason for this not being the default is to allow for DBUS-activation
of various services without showing the UI.
.SH ENVIRONMENT
.PP
.B "MODEST_DEBUG"
The MODEST_DEBUG environment may contain any number of ':'-separated strings
to trigger certain debugging features:
.PP
.IP "abort-on-warning"
Abort the program when any Gtk/Glib warning or error occurs. This can be
useful when running inside a debugger.
.IP "debug-code"
Run various pieces of debug-only code in modest
.IP "log-actions"
Log actions to the log file (not available yet)
.IP "debug-objects"
Debug GObject usage (G_TYPE_DEBUG_OBJECTS)
.IP "debug-signals"
Debug GSignal usage (G_TYPE_DEBUG_SIGNALS)
.IP "factory-settings"
Return all the user-settings to the 'factory defaults'
.SH EXIT CODES
.PP
Normally, modest will exit with 0 as its exit code. In case of any error,
the exit code will be non-zero.
.SH FILES
.PP
.IP "~/.modest/cache"
Modest e-mail cache.
.IP "~/.modest/local_folders"
Root of the local folders hierarchy (in Maildir format)
.SH BUGS
.PP
Some...  If you find one, please let us know!
.SH NO WARRANTIES
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.SH SEE ALSO
.PP
.BR mutt (3),
.BR maildir (5),
.PP
Modest Home Page: http://modest.garage.maemo.org/

.PP
.SH COPYRIGHTS
Copyright (c) 2006,2007 Nokia Corporation
All rights reserved.
.PP
.SH AUTHORS
.PP
Dirk-Jan C. Binnema and many others. Modest uses the Tinymail framework,
written by Philip Van Hoof.
