#!/bin/sh
# -*-mode:sh-*-
# Time-stamp: <2007-05-19 13:03:07 (djcb)>
#
# script to sync the external garage repository with what is inside 
# projects.maemo, without the stuff that is only useful inside
# projects.maemo.
#

LOCAL_GARAGE_DIR="$HOME/src/modest-garage"

echo "+ checking $LOCAL_GARAGE_DIR"
if [ -d $LOCAL_GARAGE_DIR ]; then
   echo "$LOCAL_GARAGE_DIR already exists"
   exit 1
fi

mkdir $LOCAL_GARAGE_DIR || {
    echo "- failed to create $LOCAL_GARAGE_DIR"
    exit 1
}

echo "+ checking out garage version"
cd $LOCAL_GARAGE_DIR
svn co https://garage.maemo.org/svn/modest/modest/trunk modest

echo "+ dumping the internal version on top"
svn export --force  https://projects.maemo.org/svn/email/modest-email/modest/trunk modest

cd modest

echo "+ removing internal stuff"
rm -rf scripts
rm ChangeLog2
rm debian/changelog

echo "+ defaulting to maemo0"
cp debian/control-maemo0 debian/control

echo "+ get the external debian/changelog"
svn up debian/changelog

echo "+ adding anything not yet in the garage repo"
#FIXME: what about files that have been removed locally?
svn add `find -type f | grep -v '.svn'` 2> /dev/null

echo "+ showing the differences"
svn diff | diffstat

echo "+ now, go to $LOCAL_GARAGE_DIR/modest, edit debian/changelog, run 'svn commit' and write a nice commit message"
